import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

export function Box({char, winner}) {
  return <span style={{
    border: '1px solid', 
    fontSize: '4rem', 
    width: '45px', 
    minHeight: '45px', 
    display: 'inline-block',
    backgroundColor: winner === true ? 'green' : 'red'
  }}>{char}</span>
}

export function Row({characters, winner}) {
  const WORD_LENGTH = 5
  const wordArr = characters.padEnd(WORD_LENGTH, ' ').split('')
  return (
    <div style={{display: 'flex'}}>
      {wordArr.map((char, idx) => {
        return <Box winner={winner} key={char + idx} char={char} />
      })}
    </div>
  )
}

export default function Home() {
  const [curChars, setCurChars] = useState('')
  const [winner, setWinner] = useState(false)
  const ANSWER = 'mouse'
  useEffect(() => {
    function updateGuess(ev) {
        setCurChars(oldDatabase => {
          console.log('old state: ' + oldDatabase)
          console.log('new state: ' + ev.key)
          if (oldDatabase.length == 5) {
            if (oldDatabase == ANSWER) {
              setWinner(true)
            }
            return oldDatabase
          } else {
            return oldDatabase + ev.key
          }
        })
    }
    document.addEventListener('keyup', updateGuess)
    return () => document.removeEventListener('keyup', updateGuess)
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Jerdle!</a>
        </h1>

      <Row characters={curChars} winner={winner} />
     
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
